<a href="https://colab.research.google.com/github/harshithakorasikha1-del/DSA-Library/blob/main/Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
"""
NumPy Linear Algebra — Examples and Exercises
===============================================

This file walks through common NumPy linear algebra operations.
Each section has:
  1. A short explanation
  2. A working example program
  3. Exercises for you to try (write your solution code right below
     the exercise, in the marked space)

Run this file directly to see all example outputs:
    python numpy_linear_algebra.py
"""

import numpy as np


def section_header(title):
    print("\n" + "=" * 60)
    print(title)
    print("=" * 60)


# ---------------------------------------------------------------
# 1. Creating Matrices and Vectors
# ---------------------------------------------------------------
def example_create_arrays():
    section_header("1. Creating Matrices and Vectors")

    v = np.array([1, 2, 3])
    A = np.array([[1, 2], [3, 4]])
    I = np.eye(3)          # identity matrix
    Z = np.zeros((2, 3))
    O = np.ones((3, 2))

    print("Vector v:\n", v)
    print("Matrix A:\n", A)
    print("Identity I:\n", I)
    print("Zeros Z:\n", Z)
    print("Ones O:\n", O)


# Exercises:
# 1a. Create a 4x4 identity matrix and print it.

def matrix():
    A = np.eye(4)
    print(A)

matrix()

# 1b. Create a 3x3 matrix filled with the number 7 (hint: np.full).

def mat():
    a = np.full((3,3),7)
    print(a)
mat()

# 1c. Create a vector of 10 evenly spaced numbers between 0 and 1
#     (hint: np.linspace).
#
# --- your code here ---

def lin():
    a = np.linspace(0,1,num=10)
    print(a)
lin()

# ---------------------------------------------------------------
# 2. Matrix Multiplication
# ---------------------------------------------------------------
def example_matrix_multiplication():
    section_header("2. Matrix Multiplication")

    A = np.array([[1, 2], [3, 4]])
    B = np.array([[5, 6], [7, 8]])

    elementwise = A * B          # element-wise multiplication
    matmul_operator = A @ B      # matrix multiplication (preferred)
    matmul_function = np.matmul(A, B)
    dot_function = np.dot(A, B)

    print("A:\n", A)
    print("B:\n", B)
    print("Element-wise A*B:\n", elementwise)
    print("Matrix mult A@B:\n", matmul_operator)
    print("np.matmul(A, B):\n", matmul_function)
    print("np.dot(A, B):\n", dot_function)


# Exercises:
# 2a. Given A = [[2, 0], [0, 2]] and B = [[1, 2], [3, 4]], compute A@B
#     by hand, then verify with NumPy.

def mul():
    A = np.array([[2, 0], [0, 2]])
    B = np.array([[1, 2], [3, 4]])
    c = A@B
    d = np.matmul(A,B)
    print(c)
    print(d)
mul()

# 2b. Multiply a 3x2 matrix by a 2x4 matrix. What shape is the result?

def shape():
    a = np.array([[1,2],[3,4],[5,6]])
    b = np.array([[1,2,3,4],[5,6,7,8]])
    c = np.dot(a,b)
    print(c.shape)
shape()

# 2c. Explain (in a comment) why A*B and A@B give different results.
#
# --- your code here ---

#A*B and A@B give different results because * performs element-wise multiplication
#while @ performs true matrix multiplication.

# ---------------------------------------------------------------
# 3. Transpose
# ---------------------------------------------------------------
def example_transpose():
    section_header("3. Transpose")

    A = np.array([[1, 2, 3], [4, 5, 6]])
    print("A:\n", A)
    print("A.T (transpose):\n", A.T)
    print("np.transpose(A):\n", np.transpose(A))


# Exercises:
# 3a. Create a 3x5 matrix and confirm its transpose has shape (5, 3).

def tran():
    a = np.array([[1,2,3,4,5],[6,7,8,9,0],[5,4,3,2,1]])
    b = np.transpose(a)
    print(b.shape)
tran()

# 3b. Verify that (A @ B).T equals B.T @ A.T for two matrices A, B.
#
# --- your code here ---

def tran2():
    a = np.array([[1,2,3,4,5],[6,7,8,9,0],[5,4,3,2,1]])
    b = np.array([[1,2,3],[4,5,6],[7,8,9],[3,2,1],[6,5,4]])
    c = (a@b).T
    d = (b.T)@(a.T)
    print(c)
    print(d)
    if np.array_equal(a,b):
        print("True")
    else:
        print("false")
tran2()

# ---------------------------------------------------------------
# 4. Determinant
# ---------------------------------------------------------------
def example_determinant():
    section_header("4. Determinant")

    A = np.array([[4, 2], [7, 6]])
    det = np.linalg.det(A)
    print("A:\n", A)
    print("Determinant of A:", det)


# Exercises:
# 4a. Compute the determinant of a 3x3 matrix of your choice.

def det():
    a = np.array([[1,2,5],[4,5,6],[7,8,9]])
    det = np.linalg.det(a)
    print(det)
det()

# 4b. Create a singular (non-invertible) matrix and show its
#     determinant is (approximately) zero.
#
# --- your code here ---

def sing():
    a = np.array([[1,2,3],[4,5,6],[7,8,9]])
    det = np.linalg.det(a)
    print(det)
sing()

# ---------------------------------------------------------------
# 5. Matrix Inverse
# ---------------------------------------------------------------
def example_inverse():
    section_header("5. Matrix Inverse")

    A = np.array([[4, 7], [2, 6]])
    A_inv = np.linalg.inv(A)
    identity_check = A @ A_inv

    print("A:\n", A)
    print("Inverse of A:\n", A_inv)
    print("A @ A_inv (should be identity):\n", identity_check)


# Exercises:
# 5a. Try to invert a singular matrix and observe the error NumPy
#     raises (hint: wrap in try/except).

def singular():
    try:
        a = np.array([[1,2,3],[4,5,6],[7,8,9]])
        a_inv = np.linalg.inv(a)
        id = a @ a_inv
        print(id)
    except np.linalg.LinAlgError as e:
        print("Singular matrix cannot be inverted!")
singular()

# 5b. Verify that (A_inv)_inv == A for a matrix of your choice.
#
# --- your code here ---

def inv():
    A = np.array([[1,2], [2,1]])
    A_inv = np.linalg.inv(A)
    A_inv_inv = np.linalg.inv(A_inv)
    if np.allclose(A_inv_inv,A):
        print("True")
    else:
        print("False")
inv()

# ---------------------------------------------------------------
# 6. Solving Systems of Linear Equations
# ---------------------------------------------------------------
def example_solve_linear_system():
    section_header("6. Solving Linear Systems (Ax = b)")

    # 2x + 3y = 8
    # 5x + 4y = 13
    A = np.array([[2, 3], [5, 4]])
    b = np.array([8, 13])

    x = np.linalg.solve(A, b)
    print("A:\n", A)
    print("b:", b)
    print("Solution x:", x)
    print("Check A @ x == b:", np.allclose(A @ x, b))


# Exercises:
# 6a. Solve the system:
#       x + y + z = 6
#       2y + 5z = -4
#       2x + 5y - z = 27

def solve():
    a = np.array([[1,1,1],[0,2,5],[2,5,-1]])
    b = np.array([6,-4,27])
    x = np.linalg.solve(a,b)
    print(x)
solve()

# 6b. Compare np.linalg.solve(A, b) with computing
#     np.linalg.inv(A) @ b. Which is generally preferred, and why?
#
# --- your code here ---

def com():
    a = np.array([[1,1,1],[0,2,5],[2,5,-1]])
    b = np.array([6,-4,27])
    x = np.linalg.solve(a,b)
    d = np.linalg.inv(a) @ b
    if np.allclose(x,d):
        print("True")
    else:
        print("False")
com()
#np.linalg.solve(A, b) is generally preferred over np.linalg.inv(A) @ b
#because it is faster and has better numerical stability.


# ---------------------------------------------------------------
# 7. Eigenvalues and Eigenvectors
# ---------------------------------------------------------------
def example_eigen():
    section_header("7. Eigenvalues and Eigenvectors")

    A = np.array([[4, -2], [1, 1]])
    eigenvalues, eigenvectors = np.linalg.eig(A)

    print("A:\n", A)
    print("Eigenvalues:", eigenvalues)
    print("Eigenvectors (columns):\n", eigenvectors)


# Exercises:
# 7a. Verify A @ v == lambda * v for each eigenvalue/eigenvector pair.

def eigen():
    A = np.array([[4, -2], [1, 1]])
    eigenvalues, eigenvectors = np.linalg.eig(A)

    for i in range(len(eigenvalues)):
        v = eigenvectors[:, i]
        print(np.allclose(A @ v, eigenvalues[i] * v))


# 7b. Find the eigenvalues of a diagonal matrix and explain the
#     pattern you notice.
#
# --- your code here ---

def eigen():
    a = np.array([[4,0,0],[0,9,0],[0,0,3]])
    eigenvalues,eigenvectors = np.linalg.eig(a)
    print(eigenvalues)
eigen()

#diagonal values are eigenvalues

# ---------------------------------------------------------------
# 8. Norms (vector and matrix length/magnitude)
# ---------------------------------------------------------------
def example_norms():
    section_header("8. Norms")

    v = np.array([3, 4])
    l2_norm = np.linalg.norm(v)          # Euclidean norm
    l1_norm = np.linalg.norm(v, ord=1)   # Manhattan norm

    print("v:", v)
    print("L2 norm (Euclidean):", l2_norm)
    print("L1 norm (Manhattan):", l1_norm)


# Exercises:
# 8a. Compute the L2 norm of a 5-dimensional vector.

def norm():
    a = np.array([1,2,3,4,5])
    norm = np.linalg.norm(a)
    print(norm)
norm()

# 8b. Normalize a vector (divide by its own norm) so its length is 1,
#     and verify the result with np.linalg.norm.
#
# --- your code here ---

def norm1():
    a = np.array([1,2,3,4,5])
    norm = np.linalg.norm(a)
    normali = a/norm
    if np.linalg.norm(normali) == 1:
        print("True")
    else:
        print("False")
norm1()

# ---------------------------------------------------------------
# 9. Rank of a Matrix
# ---------------------------------------------------------------
def example_rank():
    section_header("9. Matrix Rank")

    full_rank = np.array([[1, 2], [3, 4]])
    deficient_rank = np.array([[1, 2], [2, 4]])  # second row = 2 * first row

    print("Full-rank matrix:\n", full_rank, "-> rank =", np.linalg.matrix_rank(full_rank))
    print("Rank-deficient matrix:\n", deficient_rank, "-> rank =", np.linalg.matrix_rank(deficient_rank))


# Exercises:
# 9a. Construct a 4x4 matrix with rank 2.

def rank():
    a = np.array([[1,2,3,4],[5,6,7,8],[1,2,3,4],[5,6,7,8]])
    r = np.linalg.matrix_rank(a)
    print(r)
rank()

# 9b. Explain (in a comment) the relationship between rank and
#     whether a matrix is invertible.
#
# --- your code here ---

# The rank of an n x n square matrix A is directly tied to its invertibility:
#
# 1. Full Rank (Invertible / Non-singular):
#    If rank(A) = n, all n rows and columns are linearly independent.
#    The matrix spans the full space, meaning an inverse matrix A^-1 exists
#    such that A * A^-1 = I (the identity matrix).
#
# 2. Deficient Rank (Not invertible / Singular):
#    If rank(A) < n, the rows and columns are linearly dependent.
#    The columns do not span the entire space, the determinant is zero,
#    and the inverse matrix cannot be computed.


# ---------------------------------------------------------------
# 10. Singular Value Decomposition (SVD)
# ---------------------------------------------------------------
def example_svd():
    section_header("10. Singular Value Decomposition (SVD)")

    A = np.array([[1, 2], [3, 4], [5, 6]])
    U, S, Vt = np.linalg.svd(A)

    print("A:\n", A)
    print("U:\n", U)
    print("Singular values S:", S)
    print("V^T:\n", Vt)

    # Reconstruct A from U, S, Vt to verify decomposition
    S_full = np.zeros(A.shape)
    np.fill_diagonal(S_full, S)
    A_reconstructed = U @ S_full @ Vt
    print("Reconstructed A:\n", A_reconstructed)


# Exercises:
# 10a. Reconstruct A from its SVD components and confirm it matches
#      the original (use np.allclose).

def recon():
    A = np.array([[1, 2], [3, 4], [5, 6]])
    U, S, Vt = np.linalg.svd(A)

    S_full = np.zeros(A.shape)
    np.fill_diagonal(S_full, S)

    A_reconstructed = U @ S_full @ Vt

    print(A_reconstructed)
    print(np.allclose(A, A_reconstructed))

# 10b. Use SVD to compute a low-rank approximation of A by keeping
#      only the largest singular value. How close is it to A?
#
# --- your code here ---
def low_rank():
    A = np.array([[1, 2], [3, 4], [5, 6]])
    U, S, Vt = np.linalg.svd(A)

    S_low = np.zeros(A.shape)
    S_low[0][0] = S[0]

    A_low = U @ S_low @ Vt

    print(A_low)
    print(np.allclose(A, A_low))

if __name__ == "__main__":
    example_create_arrays()
    example_matrix_multiplication()
    example_transpose()
    example_determinant()
    example_inverse()
    example_solve_linear_system()
    example_eigen()
    example_norms()
    example_rank()
    example_svd()

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
[[7 7 7]
 [7 7 7]
 [7 7 7]]
[0.         0.11111111 0.22222222 0.33333333 0.44444444 0.55555556
 0.66666667 0.77777778 0.88888889 1.        ]
[[2 4]
 [6 8]]
[[2 4]
 [6 8]]
(3, 4)
(5, 3)
[[ 72 117  54]
 [ 69 129  63]
 [ 66 141  72]]
[[ 72 117  54]
 [ 69 129  63]
 [ 66 141  72]]
false
-6.0
0.0
Singular matrix cannot be inverted!
True
[ 5.  3. -2.]
True
[4. 9. 3.]
7.416198487095663
True
2

1. Creating Matrices and Vectors
Vector v:
 [1 2 3]
Matrix A:
 [[1 2]
 [3 4]]
Identity I:
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
Zeros Z:
 [[0. 0. 0.]
 [0. 0. 0.]]
Ones O:
 [[1. 1.]
 [1. 1.]
 [1. 1.]]

2. Matrix Multiplication
A:
 [[1 2]
 [3 4]]
B:
 [[5 6]
 [7 8]]
Element-wise A*B:
 [[ 5 12]
 [21 32]]
Matrix mult A@B:
 [[19 22]
 [43 50]]
np.matmul(A, B):
 [[19 22]
 [43 50]]
np.dot(A, B):
 [[19 22]
 [43 50]]

3. Transpose
A:
 [[1 2 3]
 [4 5 6]]
A.T (transpose):
 [[1 4]
 [2 5]
 [3 6]]
np.transpose(A):
 [[1 4]
 [2 5]
 [3 6]]

4. Determinant
A:
 [[4